version: '3.1'

services:

  unionsquare:
    image: unionsquare
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: us_admin
      MONGO_INITDB_ROOT_PASSWORD: example123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: us_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: example123
      ME_CONFIG_MONGODB_URL: mongodb://us_admin:example123@mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  us_network:
    external: true